### PR TITLE
Update to TypeScript 2.0

### PR DESCRIPTION
**Pull request by jamesrichford**
Hey,

Fixing issue #28 - seemed to be much easier than expected. All tests pass with no changes and code compiles with no errors or warnings. All looks great (obviously you did a good job to start with so no work for me! ;P)

Happy Hacktoberfest

### CODE REVIEW

**Comment by kutyel** [comment]
Actually I was thinking about compiling with the `--strictNullChecks` flag, that certainly will require some changes in the source code, plus I want to use **union types** and maybe the new type **never**, that's why this issue is not so easy to close 😉

**Comment by jamesrichford** [comment]
Missing requirements, tut tut! ;P Can you put up the details of the union types and where you want to use the never type?

**Comment by kutyel** [comment]
It would take my a long while to find out that kind of information, that is why I open-sourced the issue to #hactoberfest xDDD anyway your change will make the dependencies badge turn green again and that is good 😆

**Comment by jamesrichford** [comment]
Haha thanks. Well if you create another issue with a brief description of what your looking to come out of it I'll have a peek :)

**Pull request merged**
