### PR TITLE
Added another test for Zip method.

### PR DESCRIPTION
**Pull request by Zoxive**
Fixes Issue #31

### CODE REVIEW

**Comment by kutyel** [comment]
Awesome! Thank you so much! How did you notice that test was missing?

**Comment by Zoxive** [comment]
nyc gives you the ability to pick what reporter to use.

I basically just ran "nyc report --reporter=html" which created a coverage folder.

It will give you a detailed line by line view of every file covered, and highlight lines that are not covered.

**Comment by Zoxive** [comment]
For ease of use we could add a new script to the package.json. Then just use "npm run coverage".

https://github.com/Zoxive/linq.ts/commit/5f649b7313bfce029f4aad3c978ea351823fc93a

**Comment by kutyel** [comment]
That's great! I think it would be practical, can you also add it to the travis.yml so that valuable coverage data appears in the coverage website?

**Comment by Zoxive** [comment]
I dont have any experience using coveralls, but It appears like coveralls only supports one format from nyc "text-lcov". Which is what it currently is using. 'nyc report --reporter=text-lcov | coveralls'

It is currently creating a line by line view. https://coveralls.io/builds/8035697/source?filename=linq.js but the lines dont match up. I'm not sure how to fix this.

**Comment by kutyel** [comment]
You are right, that's why I am annoyed at coveralls, but anyway, knowing that `nyc` has more options is always good! 😉

**Pull request merged**
