### PR TITLE
Update list.ts

### PR DESCRIPTION
**Pull request by schotime**
Remove optional from PredicateType<T>

### CODE REVIEW

**Comment by kutyel** [comment]
Hi, thanks for your contribution!

Can you state the intention behind this PR? Also, the tests are not passing, what exactly do you need? 😄

**Comment by kutyel** [comment]
As you might have noticed, the optionals cannot be removed because other functions make use of this optional feature, you might not want to pass all the arguments always to the predicate, that is why it is needed:
```sh
src/list.ts:503:29 - error TS2554: Expected 3 arguments, but got 1.
503       this.Aggregate(ac => (predicate(this.ElementAt(ac)) ? ++ac : ac), 0)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/list.ts:3:36
    3 type PredicateType<T> = (value: T, index: number, list: T[]) => boolean
                                         ~~~~~~~~~~~~~
    An argument for 'index' was not provided.
src/list.ts:542:29 - error TS2554: Expected 3 arguments, but got 1.
542       this.Aggregate(ac => (predicate(this.ElementAt(ac)) ? ++ac : ac), 0)
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by schotime** [comment]
Sorry, didn't get to write this up, but every time i use `.Where(x => x.Id == 2)` i have to do this `.Where(x => x!.Id == 2)` and its a pain in the butt.

**Comment by schotime** [comment]
Can we just have the following so the value is always supplied then?
```ts
type PredicateType<T> = (value: T, index?: number, list?: T[]) => boolean
```

**Comment by kutyel** [comment]
Hi! You can try and provide a working PR, but by the way the library is constructed (underneath is just JS native array methods) I don't think it will work 😄

**Comment by schotime** [comment]
Can you reopen the PR, cause the tests won't run locally.

image

**Pull request closed without merging**
